siehe [Jupyter Notebooks | Shell Commands](/2023/10/10/jupyter_notebook.html#Shell-Commands)

## Installation & Import

In [2]:
import sys

In [3]:
sys.executable

'/opt/homebrew/opt/python@3.11/bin/python3.11'

In [4]:
!{sys.executable} -m pip install numpy

In [5]:
import numpy as np

## NumPy-Arrays vs. Listen

In [6]:
[1, 2, 3] + [100, 200, 300]

[1, 2, 3, 100, 200, 300]

In [7]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

### elementweise Operationen

In [8]:
a1 = np.array([  1,   2,   3])
#                +    +    +
a2 = np.array([100, 200, 300])

print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
print(a2 ** a1)
print(a2 // a1)
print(a1 % a2)

print()

print(a1 * 2)
print(np.sqrt(a1))
print((a2 ** (1 / a1)))

print()

print(a1 > 2)
print(a1 < 2)
print(a1 <= 2)
print(a1 >= 2)
print(a1 == 2)
print(a1 != 2)

[101 202 303]
[ -99 -198 -297]
[100 400 900]
[0.01 0.01 0.01]
[     100    40000 27000000]
[100 100 100]
[1 2 3]

[2 4 6]
[1.         1.41421356 1.73205081]
[100.          14.14213562   6.6943295 ]

[False False  True]
[ True False False]
[ True  True False]
[False  True  True]
[False  True False]
[ True False  True]


### Datentypen

bei np arrays werden alle element-typen aneinander angeglichen.

In [9]:
[1, 2.0, 2.5, 5]

[1, 2.0, 2.5, 5]

In [10]:
np.array([1, 2.0, 2.5, 5])

array([1. , 2. , 2.5, 5. ])

In [11]:
np.array([1.0, 2.0, 3.0], dtype=int)

array([1, 2, 3])

### Recheneffizienz

In [12]:
%%timeit
2 + 2

5.76 ns ± 0.0344 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [13]:
l1 = []
l2 = []

for i in range(2**17):
    l1.append(i)
    l2.append(i * 3)

print(l2[-20:])

[393156, 393159, 393162, 393165, 393168, 393171, 393174, 393177, 393180, 393183, 393186, 393189, 393192, 393195, 393198, 393201, 393204, 393207, 393210, 393213]


In [17]:
def elementwise_add_lists(l1, l2):

    result = []

    for el1, el2 in zip(l1, l2): # siehe Python-Auffrischung: zip
        result.append(el1 + el2)

    return result

[Python-Auffrischung: `zip`](/2023/10/17/python-auffrischung.html#zip)

In [18]:
%%timeit
elementwise_add_lists(l1, l2)

4.64 ms ± 37 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
a1 = np.array(l1)
a2 = np.array(l2)

In [20]:
%%timeit
a1 + a2

27.3 µs ± 630 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Arrays erstellen

### `np.array()`

In [21]:
np.array([1, 2, 3])

array([1, 2, 3])

### `np.zeros()`

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### `np.ones()`

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### `np.empty()`

In [24]:
np.empty(100)

array([1.72723371e-077, 1.72723371e-077, 1.16599492e-321, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 2.34339806e-314, 2.34339806e-314, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0

### `np.arange()`

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [28]:
np.arange(3, 10, 0.2)

array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4,
       5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. ,
       8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

### `np.linspace()`

In [29]:
np.linspace(0, 9, 9)

array([0.   , 1.125, 2.25 , 3.375, 4.5  , 5.625, 6.75 , 7.875, 9.   ])

### `np.geomspace()`

In [30]:
np.geomspace(1, 10, 10)

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

## Multidimensionale Arrays

In [31]:
np.reshape(np.linspace(1, 15, 15), (3, 5))

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

## shapes

Shapes werden in NumPy immer als Tuple angegeben, wobei die Elemente jeweils die Größe der Dimension angibt.

In [32]:
np.array([[1, 2, 3], 
          [3, 4, 5]]).shape

(2, 3)

In [33]:
a = np.reshape(np.linspace(1, 30, 30), (3, 5, 2))

print(a)

print(a.shape)

[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]
  [ 7.  8.]
  [ 9. 10.]]

 [[11. 12.]
  [13. 14.]
  [15. 16.]
  [17. 18.]
  [19. 20.]]

 [[21. 22.]
  [23. 24.]
  [25. 26.]
  [27. 28.]
  [29. 30.]]]
(3, 5, 2)


## Auf Elemente zugreifen

### 1D

siehe [Python Auffrischung: Indizieren](/2023/10/17/python-auffrischung.html#Listen-Indizierung-und--Slicing:)

### m-D

In [34]:
print(a, '\n')

print(a[1], '\n')

print(a[1][2], '\n')
print(a[1][2][1], '\n')

[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]
  [ 7.  8.]
  [ 9. 10.]]

 [[11. 12.]
  [13. 14.]
  [15. 16.]
  [17. 18.]
  [19. 20.]]

 [[21. 22.]
  [23. 24.]
  [25. 26.]
  [27. 28.]
  [29. 30.]]] 

[[11. 12.]
 [13. 14.]
 [15. 16.]
 [17. 18.]
 [19. 20.]] 

[15. 16.] 

16.0 



In [35]:
a = np.reshape(np.linspace(1, 45, 45), (3, 5, 3))

print(a, '\n')

print(a[1], '\n')

print(a[1, 2], '\n')
print(a[1, 2, 1], '\n')

print(a[1, 2, 0:2], '\n')

print(a[1:3, 2:4, 0:2], '\n')

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]
  [28. 29. 30.]]

 [[31. 32. 33.]
  [34. 35. 36.]
  [37. 38. 39.]
  [40. 41. 42.]
  [43. 44. 45.]]] 

[[16. 17. 18.]
 [19. 20. 21.]
 [22. 23. 24.]
 [25. 26. 27.]
 [28. 29. 30.]] 

[22. 23. 24.] 

23.0 

[22. 23.] 

[[[22. 23.]
  [25. 26.]]

 [[37. 38.]
  [40. 41.]]] 



### `np.newaxis`

In [36]:
a1 = np.array([1, 2, 3])
a2 = a1 * 100

print(a1[:, np.newaxis] * a2)

[[100 200 300]
 [200 400 600]
 [300 600 900]]


### egal wie viele Dimensionen: boolsche Indizes

In [37]:
b_i = a1 > 2 # bool index

print(b_i)

print(a1[b_i])

md_a = a1[:, np.newaxis] * a2

print(md_a)

print(md_a > 300)

print(md_a[md_a > 300])

[False False  True]
[3]
[[100 200 300]
 [200 400 600]
 [300 600 900]]
[[False False False]
 [False  True  True]
 [False  True  True]]
[400 600 600 900]
